Name = "カレーせんべい1"
Image = "currysenbei.png"
SkillName = "どう見ても〄マーク"
Description = '''
${reset}ゲージブースト ${blue}${bold}(160%)
${reset}ダメージ無効化 ${green}${bold}(25回)
'''

[[Abilities]]
Type = "Boost"
Arguments = { bonus = 0.6 }

[[Abilities]]
Type = "DamageGuard"
Arguments = { count = 25 }
