Name = "kb10uy"
Image = "kb10uy.png"
SkillName = "イ゛ェアアアア"
Description = '''
${reset}AIRボーナス ${blue}${bold}(+200)
${reset}AIR-ACTボーナス ${blue}${bold}(+500)
${reset}それ以外ペナルティ ${red}${bold}(-10)
'''

[[Abilities]]
Type = "AirBoost"
Arguments = { air = 200, airact = 500, other = -10 }